name: main build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Dotnet Installation Info
        run: dotnet --info

      - name: Build
        run: dotnet build

      - name: Lint
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --no-build --verbosity normal
