name: main build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7

      - name: Install Dotnet
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a
        with:
          dotnet-version: "7.0.x"

      - name: Dotnet Installation Info
        run: dotnet --info

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build --verbosity normal
